const formsPraktisch = [
  ["praktisch", "Verantwoordelijkheid", "focus1", "vraag1A", "antwoord1A"],
  ["praktisch", "Verantwoordelijkheid", "focus1", "vraag1B", "antwoord1B"],
  ["praktisch", "Verantwoordelijkheid", "focus1", "vraag1C", "antwoord1C"],
  ["praktisch", "Verantwoordelijkheid", "focus1", "vraag1D", "antwoord1D"],
  ["praktisch", "Verantwoordelijkheid", "focus1", "vraag1E", "antwoord1E"],
  ["praktisch", "Verantwoordelijkheid", "focus1", "vraag1F", "antwoord1F"],

  ["praktisch", "Verantwoordelijkheid", "focus2", "vraag2A", "antwoord2A"],
  ["praktisch", "Verantwoordelijkheid", "focus2", "vraag2B", "antwoord2B"],
  ["praktisch", "Verantwoordelijkheid", "focus2", "vraag2C", "antwoord2C"],
  ["praktisch", "Verantwoordelijkheid", "focus2", "vraag2D", "antwoord2D"],
  ["praktisch", "Verantwoordelijkheid", "focus2", "vraag2E", "antwoord2E"],
  ["praktisch", "Verantwoordelijkheid", "focus2", "vraag2F", "antwoord2F"],

  ["praktisch", "Verantwoordelijkheid", "focus3", "vraag3A", "antwoord3A"],
  ["praktisch", "Verantwoordelijkheid", "focus3", "vraag3B", "antwoord3B"],
  ["praktisch", "Verantwoordelijkheid", "focus3", "vraag3C", "antwoord3C"],
  ["praktisch", "Verantwoordelijkheid", "focus3", "vraag3D", "antwoord3D"],
  ["praktisch", "Verantwoordelijkheid", "focus3", "vraag3E", "antwoord3E"],
  ["praktisch", "Verantwoordelijkheid", "focus3", "vraag3F", "antwoord3F"],

  ["praktisch", "Verantwoordelijkheid", "focus4", "vraag4A", "antwoord4A"],
  ["praktisch", "Verantwoordelijkheid", "focus4", "vraag4B", "antwoord4B"],
  ["praktisch", "Verantwoordelijkheid", "focus4", "vraag4C", "antwoord4C"],
  ["praktisch", "Verantwoordelijkheid", "focus4", "vraag4D", "antwoord4D"],
  ["praktisch", "Verantwoordelijkheid", "focus4", "vraag4E", "antwoord4E"],
  ["praktisch", "Verantwoordelijkheid", "focus4", "vraag4F", "antwoord4F"],

  ["praktisch", "Verantwoordelijkheid", "focus5", "vraag5A", "antwoord5A"],
  ["praktisch", "Verantwoordelijkheid", "focus5", "vraag5B", "antwoord5B"],
  ["praktisch", "Verantwoordelijkheid", "focus5", "vraag5C", "antwoord5C"],
  ["praktisch", "Verantwoordelijkheid", "focus5", "vraag5D", "antwoord5D"],
  ["praktisch", "Verantwoordelijkheid", "focus5", "vraag5E", "antwoord5E"],
  ["praktisch", "Verantwoordelijkheid", "focus5", "vraag5F", "antwoord5F"],

  ["praktisch", "Verantwoordelijkheid", "focus6", "vraag6A", "antwoord6A"],
  ["praktisch", "Verantwoordelijkheid", "focus6", "vraag6B", "antwoord6B"],
  ["praktisch", "Verantwoordelijkheid", "focus6", "vraag6C", "antwoord6C"],
  ["praktisch", "Verantwoordelijkheid", "focus6", "vraag6D", "antwoord6D"],
  ["praktisch", "Verantwoordelijkheid", "focus6", "vraag6E", "antwoord6E"],
  ["praktisch", "Verantwoordelijkheid", "focus6", "vraag6F", "antwoord6F"],

  ["praktisch", "thema2", "focus1", "vraag1A", "antwoord1A"],
  ["praktisch", "thema2", "focus1", "vraag1B", "antwoord1B"],
  ["praktisch", "thema2", "focus1", "vraag1C", "antwoord1C"],
  ["praktisch", "thema2", "focus1", "vraag1D", "antwoord1D"],
  ["praktisch", "thema2", "focus1", "vraag1E", "antwoord1E"],
  ["praktisch", "thema2", "focus1", "vraag1F", "antwoord1F"],

  ["praktisch", "thema2", "focus2", "vraag2A", "antwoord2A"],
  ["praktisch", "thema2", "focus2", "vraag2B", "antwoord2B"],
  ["praktisch", "thema2", "focus2", "vraag2C", "antwoord2C"],
  ["praktisch", "thema2", "focus2", "vraag2D", "antwoord2D"],
  ["praktisch", "thema2", "focus2", "vraag2E", "antwoord2E"],
  ["praktisch", "thema2", "focus2", "vraag2F", "antwoord2F"],

  ["praktisch", "thema2", "focus3", "vraag3A", "antwoord3A"],
  ["praktisch", "thema2", "focus3", "vraag3B", "antwoord3B"],
  ["praktisch", "thema2", "focus3", "vraag3C", "antwoord3C"],
  ["praktisch", "thema2", "focus3", "vraag3D", "antwoord3D"],
  ["praktisch", "thema2", "focus3", "vraag3E", "antwoord3E"],
  ["praktisch", "thema2", "focus3", "vraag3F", "antwoord3F"],

  ["praktisch", "thema2", "focus4", "vraag4A", "antwoord4A"],
  ["praktisch", "thema2", "focus4", "vraag4B", "antwoord4B"],
  ["praktisch", "thema2", "focus4", "vraag4C", "antwoord4C"],
  ["praktisch", "thema2", "focus4", "vraag4D", "antwoord4D"],
  ["praktisch", "thema2", "focus4", "vraag4E", "antwoord4E"],
  ["praktisch", "thema2", "focus4", "vraag4F", "antwoord4F"],

  ["praktisch", "thema2", "focus5", "vraag5A", "antwoord5A"],
  ["praktisch", "thema2", "focus5", "vraag5B", "antwoord5B"],
  ["praktisch", "thema2", "focus5", "vraag5C", "antwoord5C"],
  ["praktisch", "thema2", "focus5", "vraag5D", "antwoord5D"],
  ["praktisch", "thema2", "focus5", "vraag5E", "antwoord5E"],
  ["praktisch", "thema2", "focus5", "vraag5F", "antwoord5F"],

  ["praktisch", "thema2", "focus6", "vraag6A", "antwoord6A"],
  ["praktisch", "thema2", "focus6", "vraag6B", "antwoord6B"],
  ["praktisch", "thema2", "focus6", "vraag6C", "antwoord6C"],
  ["praktisch", "thema2", "focus6", "vraag6D", "antwoord6D"],
  ["praktisch", "thema2", "focus6", "vraag6E", "antwoord6E"],
  ["praktisch", "thema2", "focus6", "vraag6F", "antwoord6F"],

  ["praktisch", "thema3", "focus1", "vraag1A", "antwoord1A"],
  ["praktisch", "thema3", "focus1", "vraag1B", "antwoord1B"],
  ["praktisch", "thema3", "focus1", "vraag1C", "antwoord1C"],
  ["praktisch", "thema3", "focus1", "vraag1D", "antwoord1D"],
  ["praktisch", "thema3", "focus1", "vraag1E", "antwoord1E"],
  ["praktisch", "thema3", "focus1", "vraag1F", "antwoord1F"],

  ["praktisch", "thema3", "focus2", "vraag2A", "antwoord2A"],
  ["praktisch", "thema3", "focus2", "vraag2B", "antwoord2B"],
  ["praktisch", "thema3", "focus2", "vraag2C", "antwoord2C"],
  ["praktisch", "thema3", "focus2", "vraag2D", "antwoord2D"],
  ["praktisch", "thema3", "focus2", "vraag2E", "antwoord2E"],
  ["praktisch", "thema3", "focus2", "vraag2F", "antwoord2F"],

  ["praktisch", "thema3", "focus3", "vraag3A", "antwoord3A"],
  ["praktisch", "thema3", "focus3", "vraag3B", "antwoord3B"],
  ["praktisch", "thema3", "focus3", "vraag3C", "antwoord3C"],
  ["praktisch", "thema3", "focus3", "vraag3D", "antwoord3D"],
  ["praktisch", "thema3", "focus3", "vraag3E", "antwoord3E"],
  ["praktisch", "thema3", "focus3", "vraag3F", "antwoord3F"],

  ["praktisch", "thema3", "focus4", "vraag4A", "antwoord4A"],
  ["praktisch", "thema3", "focus4", "vraag4B", "antwoord4B"],
  ["praktisch", "thema3", "focus4", "vraag4C", "antwoord4C"],
  ["praktisch", "thema3", "focus4", "vraag4D", "antwoord4D"],
  ["praktisch", "thema3", "focus4", "vraag4E", "antwoord4E"],
  ["praktisch", "thema3", "focus4", "vraag4F", "antwoord4F"],

  ["praktisch", "thema3", "focus5", "vraag5A", "antwoord5A"],
  ["praktisch", "thema3", "focus5", "vraag5B", "antwoord5B"],
  ["praktisch", "thema3", "focus5", "vraag5C", "antwoord5C"],
  ["praktisch", "thema3", "focus5", "vraag5D", "antwoord5D"],
  ["praktisch", "thema3", "focus5", "vraag5E", "antwoord5E"],
  ["praktisch", "thema3", "focus5", "vraag5F", "antwoord5F"],

  ["praktisch", "thema3", "focus6", "vraag6A", "antwoord6A"],
  ["praktisch", "thema3", "focus6", "vraag6B", "antwoord6B"],
  ["praktisch", "thema3", "focus6", "vraag6C", "antwoord6C"],
  ["praktisch", "thema3", "focus6", "vraag6D", "antwoord6D"],
  ["praktisch", "thema3", "focus6", "vraag6E", "antwoord6E"],
  ["praktisch", "thema3", "focus6", "vraag6F", "antwoord6F"],

  ["praktisch", "thema4", "focus1", "vraag1A", "antwoord1A"],
  ["praktisch", "thema4", "focus1", "vraag1B", "antwoord1B"],
  ["praktisch", "thema4", "focus1", "vraag1C", "antwoord1C"],
  ["praktisch", "thema4", "focus1", "vraag1D", "antwoord1D"],
  ["praktisch", "thema4", "focus1", "vraag1E", "antwoord1E"],
  ["praktisch", "thema4", "focus1", "vraag1F", "antwoord1F"],

  ["praktisch", "thema4", "focus2", "vraag2A", "antwoord2A"],
  ["praktisch", "thema4", "focus2", "vraag2B", "antwoord2B"],
  ["praktisch", "thema4", "focus2", "vraag2C", "antwoord2C"],
  ["praktisch", "thema4", "focus2", "vraag2D", "antwoord2D"],
  ["praktisch", "thema4", "focus2", "vraag2E", "antwoord2E"],
  ["praktisch", "thema4", "focus2", "vraag2F", "antwoord2F"],

  ["praktisch", "thema4", "focus3", "vraag3A", "antwoord3A"],
  ["praktisch", "thema4", "focus3", "vraag3B", "antwoord3B"],
  ["praktisch", "thema4", "focus3", "vraag3C", "antwoord3C"],
  ["praktisch", "thema4", "focus3", "vraag3D", "antwoord3D"],
  ["praktisch", "thema4", "focus3", "vraag3E", "antwoord3E"],
  ["praktisch", "thema4", "focus3", "vraag3F", "antwoord3F"],

  ["praktisch", "thema4", "focus4", "vraag4A", "antwoord4A"],
  ["praktisch", "thema4", "focus4", "vraag4B", "antwoord4B"],
  ["praktisch", "thema4", "focus4", "vraag4C", "antwoord4C"],
  ["praktisch", "thema4", "focus4", "vraag4D", "antwoord4D"],
  ["praktisch", "thema4", "focus4", "vraag4E", "antwoord4E"],
  ["praktisch", "thema4", "focus4", "vraag4F", "antwoord4F"],

  ["praktisch", "thema4", "focus5", "vraag5A", "antwoord5A"],
  ["praktisch", "thema4", "focus5", "vraag5B", "antwoord5B"],
  ["praktisch", "thema4", "focus5", "vraag5C", "antwoord5C"],
  ["praktisch", "thema4", "focus5", "vraag5D", "antwoord5D"],
  ["praktisch", "thema4", "focus5", "vraag5E", "antwoord5E"],
  ["praktisch", "thema4", "focus5", "vraag5F", "antwoord5F"],

  ["praktisch", "thema4", "focus6", "vraag6A", "antwoord6A"],
  ["praktisch", "thema4", "focus6", "vraag6B", "antwoord6B"],
  ["praktisch", "thema4", "focus6", "vraag6C", "antwoord6C"],
  ["praktisch", "thema4", "focus6", "vraag6D", "antwoord6D"],
  ["praktisch", "thema4", "focus6", "vraag6E", "antwoord6E"],
  ["praktisch", "thema4", "focus6", "vraag6F", "antwoord6F"],

  ["praktisch", "thema5", "focus1", "vraag1A", "antwoord1A"],
  ["praktisch", "thema5", "focus1", "vraag1B", "antwoord1B"],
  ["praktisch", "thema5", "focus1", "vraag1C", "antwoord1C"],
  ["praktisch", "thema5", "focus1", "vraag1D", "antwoord1D"],
  ["praktisch", "thema5", "focus1", "vraag1E", "antwoord1E"],
  ["praktisch", "thema5", "focus1", "vraag1F", "antwoord1F"],

  ["praktisch", "thema5", "focus2", "vraag2A", "antwoord2A"],
  ["praktisch", "thema5", "focus2", "vraag2B", "antwoord2B"],
  ["praktisch", "thema5", "focus2", "vraag2C", "antwoord2C"],
  ["praktisch", "thema5", "focus2", "vraag2D", "antwoord2D"],
  ["praktisch", "thema5", "focus2", "vraag2E", "antwoord2E"],
  ["praktisch", "thema5", "focus2", "vraag2F", "antwoord2F"],

  ["praktisch", "thema5", "focus3", "vraag3A", "antwoord3A"],
  ["praktisch", "thema5", "focus3", "vraag3B", "antwoord3B"],
  ["praktisch", "thema5", "focus3", "vraag3C", "antwoord3C"],
  ["praktisch", "thema5", "focus3", "vraag3D", "antwoord3D"],
  ["praktisch", "thema5", "focus3", "vraag3E", "antwoord3E"],
  ["praktisch", "thema5", "focus3", "vraag3F", "antwoord3F"],

  ["praktisch", "thema5", "focus4", "vraag4A", "antwoord4A"],
  ["praktisch", "thema5", "focus4", "vraag4B", "antwoord4B"],
  ["praktisch", "thema5", "focus4", "vraag4C", "antwoord4C"],
  ["praktisch", "thema5", "focus4", "vraag4D", "antwoord4D"],
  ["praktisch", "thema5", "focus4", "vraag4E", "antwoord4E"],
  ["praktisch", "thema5", "focus4", "vraag4F", "antwoord4F"],

  ["praktisch", "thema5", "focus5", "vraag5A", "antwoord5A"],
  ["praktisch", "thema5", "focus5", "vraag5B", "antwoord5B"],
  ["praktisch", "thema5", "focus5", "vraag5C", "antwoord5C"],
  ["praktisch", "thema5", "focus5", "vraag5D", "antwoord5D"],
  ["praktisch", "thema5", "focus5", "vraag5E", "antwoord5E"],
  ["praktisch", "thema5", "focus5", "vraag5F", "antwoord5F"],

  ["praktisch", "thema5", "focus6", "vraag6A", "antwoord6A"],
  ["praktisch", "thema5", "focus6", "vraag6B", "antwoord6B"],
  ["praktisch", "thema5", "focus6", "vraag6C", "antwoord6C"],
  ["praktisch", "thema5", "focus6", "vraag6D", "antwoord6D"],
  ["praktisch", "thema5", "focus6", "vraag6E", "antwoord6E"],
  ["praktisch", "thema5", "focus6", "vraag6F", "antwoord6F"],

  ["praktisch", "thema6", "focus1", "vraag1A", "antwoord1A"],
  ["praktisch", "thema6", "focus1", "vraag1B", "antwoord1B"],
  ["praktisch", "thema6", "focus1", "vraag1C", "antwoord1C"],
  ["praktisch", "thema6", "focus1", "vraag1D", "antwoord1D"],
  ["praktisch", "thema6", "focus1", "vraag1E", "antwoord1E"],
  ["praktisch", "thema6", "focus1", "vraag1F", "antwoord1F"],

  ["praktisch", "thema6", "focus2", "vraag2A", "antwoord2A"],
  ["praktisch", "thema6", "focus2", "vraag2B", "antwoord2B"],
  ["praktisch", "thema6", "focus2", "vraag2C", "antwoord2C"],
  ["praktisch", "thema6", "focus2", "vraag2D", "antwoord2D"],
  ["praktisch", "thema6", "focus2", "vraag2E", "antwoord2E"],
  ["praktisch", "thema6", "focus2", "vraag2F", "antwoord2F"],

  ["praktisch", "thema6", "focus3", "vraag3A", "antwoord3A"],
  ["praktisch", "thema6", "focus3", "vraag3B", "antwoord3B"],
  ["praktisch", "thema6", "focus3", "vraag3C", "antwoord3C"],
  ["praktisch", "thema6", "focus3", "vraag3D", "antwoord3D"],
  ["praktisch", "thema6", "focus3", "vraag3E", "antwoord3E"],
  ["praktisch", "thema6", "focus3", "vraag3F", "antwoord3F"],

  ["praktisch", "thema6", "focus4", "vraag4A", "antwoord4A"],
  ["praktisch", "thema6", "focus4", "vraag4B", "antwoord4B"],
  ["praktisch", "thema6", "focus4", "vraag4C", "antwoord4C"],
  ["praktisch", "thema6", "focus4", "vraag4D", "antwoord4D"],
  ["praktisch", "thema6", "focus4", "vraag4E", "antwoord4E"],
  ["praktisch", "thema6", "focus4", "vraag4F", "antwoord4F"],

  ["praktisch", "thema6", "focus5", "vraag5A", "antwoord5A"],
  ["praktisch", "thema6", "focus5", "vraag5B", "antwoord5B"],
  ["praktisch", "thema6", "focus5", "vraag5C", "antwoord5C"],
  ["praktisch", "thema6", "focus5", "vraag5D", "antwoord5D"],
  ["praktisch", "thema6", "focus5", "vraag5E", "antwoord5E"],
  ["praktisch", "thema6", "focus5", "vraag5F", "antwoord5F"],

  ["praktisch", "thema6", "focus6", "vraag6A", "antwoord6A"],
  ["praktisch", "thema6", "focus6", "vraag6B", "antwoord6B"],
  ["praktisch", "thema6", "focus6", "vraag6C", "antwoord6C"],
  ["praktisch", "thema6", "focus6", "vraag6D", "antwoord6D"],
  ["praktisch", "thema6", "focus6", "vraag6E", "antwoord6E"],
  ["praktisch", "thema6", "focus6", "vraag6F", "antwoord6F"],
];
